import { resolve } from "path";
import { useEffect, useState } from "react";
import XLSX from "xlsx";

export const verifiFile = (file: File, colunms: string[]) => {
  return new Promise<boolean>((resolve, x) => {
    const reader = new FileReader();
    reader.onload = (e: any) => {
      const bufferArray = e.target.result;
      const wb = XLSX.read(bufferArray, { type: "buffer" });
      const wsname = wb.SheetNames[0];
      const ws = wb.Sheets[wsname];
      const data: any = XLSX.utils.sheet_to_json(ws, { header: 1 })[0];
      const colunmsfilter = colunms.find((e) => !data.includes(e));
      resolve(colunmsfilter ? false : true);
    };
    reader.readAsArrayBuffer(file);
  });
};

export const color = [
  "#1f77b4",
  "#aec7e8",
  "#ff7f0e",
  "#ffbb78",
  "#2ca02c",
  "#98df8a",
  "#d62728",
  "#ff9896",
  "#9467bd",
  "#c5b0d5",
  "#8c564b",
  "#c49c94",
  "#e377c2",
  "#f7b6d2",
  "#7f7f7f",
  "#c7c7c7",
  "#bcbd22",
  "#dbdb8d",
  "#17becf",
  "#9edae5",
];

export const descSubcodigos = [
  { subcodigo: 1001, descripcion: "INSTALAR PREVENTOR DE ARIETES" },
  { subcodigo: 1002, descripcion: "DESINSTALAR PREVENTOR DE ARIETES" },
  {
    subcodigo: 1003,
    descripcion: "INSTALAR / DESINSTALAR ADAPTADOR DE FLANGE",
  },
  { subcodigo: 1004, descripcion: "INSTALAR / DESINSTALAR ARBOL DE NAVIDAD" },
  { subcodigo: 1005, descripcion: "INSTALAR / DESINSTALAR ADAPTADOR SPOOL" },
  {
    subcodigo: 1006,
    descripcion: "INSTALAR / DESINSTALAR SOLDAR PROBAR CASING HEAD",
  },
  { subcodigo: 1007, descripcion: "CORTAR BISELAR CASING" },
  { subcodigo: 1008, descripcion: "CAMBIO DE PIPE RAMS / PREVENTOR ANULAR" },
  { subcodigo: 1009, descripcion: "PRUEBA DE PREVENTORES" },
  { subcodigo: 1010, descripcion: "COLGANDO REVESTIMIENTO" },
  { subcodigo: 1011, descripcion: "No Defino" },
  { subcodigo: 1012, descripcion: "No Defino" },
  { subcodigo: 1013, descripcion: "No Defino" },
  { subcodigo: 1014, descripcion: "No Defino" },
  { subcodigo: 1015, descripcion: "No Defino" },
  { subcodigo: 1016, descripcion: "No Defino" },
  { subcodigo: 1017, descripcion: "No Defino" },
  { subcodigo: 1018, descripcion: "No Defino" },
  { subcodigo: 1019, descripcion: "No Defino" },
  { subcodigo: 1020, descripcion: "No Defino" },
  { subcodigo: 1021, descripcion: "No Defino" },
  { subcodigo: 1022, descripcion: "No Defino" },
  { subcodigo: 1023, descripcion: "No Defino" },
  { subcodigo: 1024, descripcion: "No Defino" },
  { subcodigo: 1025, descripcion: "No Defino" },
  { subcodigo: 1026, descripcion: "No Defino" },
  { subcodigo: 1027, descripcion: "No Defino" },
  { subcodigo: 1028, descripcion: "No Defino" },
  { subcodigo: 1029, descripcion: "No Defino" },
  { subcodigo: 1030, descripcion: "No Defino" },
  { subcodigo: 1031, descripcion: "No Defino" },
  { subcodigo: 1032, descripcion: "No Defino" },
  { subcodigo: 1033, descripcion: "No Defino" },
  { subcodigo: 1034, descripcion: "No Defino" },
  { subcodigo: 1035, descripcion: "No Defino" },
  { subcodigo: 1036, descripcion: "No Defino" },
  { subcodigo: 1037, descripcion: "No Defino" },
  { subcodigo: 1038, descripcion: "No Defino" },
  { subcodigo: 1039, descripcion: "No Defino" },
  { subcodigo: 1040, descripcion: "No Defino" },
  { subcodigo: 1041, descripcion: "No Defino" },
  { subcodigo: 1042, descripcion: "No Defino" },
  { subcodigo: 1043, descripcion: "No Defino" },
  { subcodigo: 1044, descripcion: "No Defino" },
  { subcodigo: 1045, descripcion: "No Defino" },
  { subcodigo: 1046, descripcion: "No Defino" },
  { subcodigo: 1047, descripcion: "No Defino" },
  { subcodigo: 1048, descripcion: "No Defino" },
  { subcodigo: 1049, descripcion: "No Defino" },
  { subcodigo: 1050, descripcion: "No Defino" },
  { subcodigo: 1051, descripcion: "No Defino" },
  { subcodigo: 1052, descripcion: "No Defino" },
  { subcodigo: 1053, descripcion: "No Defino" },
  { subcodigo: 1054, descripcion: "No Defino" },
  { subcodigo: 1055, descripcion: "No Defino" },
  { subcodigo: 1056, descripcion: "No Defino" },
  { subcodigo: 1057, descripcion: "No Defino" },
  { subcodigo: 1058, descripcion: "No Defino" },
  { subcodigo: 1059, descripcion: "No Defino" },
  { subcodigo: 1060, descripcion: "No Defino" },
  { subcodigo: 1061, descripcion: "No Defino" },
  { subcodigo: 1062, descripcion: "No Defino" },
  { subcodigo: 1063, descripcion: "No Defino" },
  { subcodigo: 1064, descripcion: "No Defino" },
  { subcodigo: 1065, descripcion: "No Defino" },
  { subcodigo: 1066, descripcion: "No Defino" },
  { subcodigo: 1067, descripcion: "No Defino" },
  { subcodigo: 1068, descripcion: "No Defino" },
  { subcodigo: 1069, descripcion: "No Defino" },
  { subcodigo: 1070, descripcion: "No Defino" },
  { subcodigo: 1071, descripcion: "No Defino" },
  { subcodigo: 1072, descripcion: "No Defino" },
  { subcodigo: 1073, descripcion: "No Defino" },
  { subcodigo: 1074, descripcion: "No Defino" },
  { subcodigo: 1075, descripcion: "No Defino" },
  { subcodigo: 1076, descripcion: "No Defino" },
  { subcodigo: 1077, descripcion: "No Defino" },
  { subcodigo: 1078, descripcion: "No Defino" },
  { subcodigo: 1079, descripcion: "No Defino" },
  { subcodigo: 1080, descripcion: "No Defino" },
  { subcodigo: 1081, descripcion: "No Defino" },
  { subcodigo: 1082, descripcion: "No Defino" },
  { subcodigo: 1083, descripcion: "No Defino" },
  { subcodigo: 1084, descripcion: "No Defino" },
  { subcodigo: 1085, descripcion: "No Defino" },
  { subcodigo: 1086, descripcion: "No Defino" },
  { subcodigo: 1087, descripcion: "No Defino" },
  { subcodigo: 1088, descripcion: "No Defino" },
  { subcodigo: 1089, descripcion: "No Defino" },
  { subcodigo: 1090, descripcion: "No Defino" },
  { subcodigo: 1091, descripcion: "No Defino" },
  { subcodigo: 1092, descripcion: "No Defino" },
  { subcodigo: 1093, descripcion: "No Defino" },
  { subcodigo: 1094, descripcion: "No Defino" },
  { subcodigo: 1095, descripcion: "No Defino" },
  { subcodigo: 1096, descripcion: "No Defino" },
  { subcodigo: 1097, descripcion: "No Defino" },
  { subcodigo: 1098, descripcion: "No Defino" },
  { subcodigo: 1099, descripcion: "No Defino" },
  { subcodigo: 1100, descripcion: "No Defino" },
  { subcodigo: 1101, descripcion: "VIAJE CORTO" },
  {
    subcodigo: 1102,
    descripcion: "VIAJE DE ACONDICIONAMIENTO ASOCIADO A OP DE LOGGING",
  },
  {
    subcodigo: 1103,
    descripcion: "VIAJE DE ACONDICIONAMIENTO ASOCIADO A OP CON CASING",
  },
  {
    subcodigo: 1104,
    descripcion: "VIAJE DE ACONDICIONAMIENTO ASOCIADO A OP DE DRILLING",
  },
  { subcodigo: 1105, descripcion: "No Defino" },
  {
    subcodigo: 1106,
    descripcion: "VIAJE DE ACONDICIONAMIENTO ASOCIADO A OP DE CORING",
  },
  { subcodigo: 1107, descripcion: "SACANDO BHA DRILLING" },
  { subcodigo: 1108, descripcion: "No Defino" },
  { subcodigo: 1109, descripcion: "SACANDO BHA FISHING" },
  { subcodigo: 1110, descripcion: "BAJANDO BHA DRILLING" },
  { subcodigo: 1111, descripcion: "BAJANDO BHA CORING" },
  { subcodigo: 1112, descripcion: "BAJANDO BHA FISHING" },
  { subcodigo: 1113, descripcion: "RIMANDO HACIA ARRIBA HUEVO APRETADO" },
  { subcodigo: 1114, descripcion: "RIMANDO HUEVO APRETADO" },
  { subcodigo: 1115, descripcion: "TRABAJANDO SARTA DE TUBERIA" },
  { subcodigo: 1116, descripcion: "SACANDO SARTA DE TRABAJO" },
  { subcodigo: 1117, descripcion: "BAJANDO SARTA DE TRABAJO" },
  { subcodigo: 1118, descripcion: "No Defino" },
  { subcodigo: 1119, descripcion: "No Defino" },
  { subcodigo: 1120, descripcion: "No Defino" },
  { subcodigo: 1121, descripcion: "No Defino" },
  { subcodigo: 1122, descripcion: "No Defino" },
  { subcodigo: 1123, descripcion: "No Defino" },
  { subcodigo: 1124, descripcion: "No Defino" },
  { subcodigo: 1125, descripcion: "No Defino" },
  { subcodigo: 1126, descripcion: "No Defino" },
  { subcodigo: 1127, descripcion: "No Defino" },
  { subcodigo: 1128, descripcion: "No Defino" },
  { subcodigo: 1129, descripcion: "No Defino" },
  { subcodigo: 1130, descripcion: "No Defino" },
  { subcodigo: 1131, descripcion: "No Defino" },
  { subcodigo: 1132, descripcion: "No Defino" },
  { subcodigo: 1133, descripcion: "No Defino" },
  { subcodigo: 1134, descripcion: "No Defino" },
  { subcodigo: 1135, descripcion: "No Defino" },
  { subcodigo: 1136, descripcion: "No Defino" },
  { subcodigo: 1137, descripcion: "No Defino" },
  { subcodigo: 1138, descripcion: "No Defino" },
  { subcodigo: 1139, descripcion: "No Defino" },
  { subcodigo: 1140, descripcion: "No Defino" },
  { subcodigo: 1141, descripcion: "No Defino" },
  { subcodigo: 1142, descripcion: "No Defino" },
  { subcodigo: 1143, descripcion: "No Defino" },
  { subcodigo: 1144, descripcion: "No Defino" },
  { subcodigo: 1145, descripcion: "No Defino" },
  { subcodigo: 1146, descripcion: "No Defino" },
  { subcodigo: 1147, descripcion: "No Defino" },
  { subcodigo: 1148, descripcion: "No Defino" },
  { subcodigo: 1149, descripcion: "No Defino" },
  { subcodigo: 1150, descripcion: "No Defino" },
  { subcodigo: 1151, descripcion: "No Defino" },
  { subcodigo: 1152, descripcion: "No Defino" },
  { subcodigo: 1153, descripcion: "No Defino" },
  { subcodigo: 1154, descripcion: "No Defino" },
  { subcodigo: 1155, descripcion: "No Defino" },
  { subcodigo: 1156, descripcion: "No Defino" },
  { subcodigo: 1157, descripcion: "No Defino" },
  { subcodigo: 1158, descripcion: "No Defino" },
  { subcodigo: 1159, descripcion: "No Defino" },
  { subcodigo: 1160, descripcion: "No Defino" },
  { subcodigo: 1161, descripcion: "No Defino" },
  { subcodigo: 1162, descripcion: "No Defino" },
  { subcodigo: 1163, descripcion: "No Defino" },
  { subcodigo: 1164, descripcion: "No Defino" },
  { subcodigo: 1165, descripcion: "No Defino" },
  { subcodigo: 1166, descripcion: "No Defino" },
  { subcodigo: 1167, descripcion: "No Defino" },
  { subcodigo: 1168, descripcion: "No Defino" },
  { subcodigo: 1169, descripcion: "No Defino" },
  { subcodigo: 1170, descripcion: "No Defino" },
  { subcodigo: 1171, descripcion: "No Defino" },
  { subcodigo: 1172, descripcion: "No Defino" },
  { subcodigo: 1173, descripcion: "No Defino" },
  { subcodigo: 1174, descripcion: "No Defino" },
  { subcodigo: 1175, descripcion: "No Defino" },
  { subcodigo: 1176, descripcion: "No Defino" },
  { subcodigo: 1177, descripcion: "No Defino" },
  { subcodigo: 1178, descripcion: "No Defino" },
  { subcodigo: 1179, descripcion: "No Defino" },
  { subcodigo: 1180, descripcion: "No Defino" },
  { subcodigo: 1181, descripcion: "No Defino" },
  { subcodigo: 1182, descripcion: "No Defino" },
  { subcodigo: 1183, descripcion: "No Defino" },
  { subcodigo: 1184, descripcion: "No Defino" },
  { subcodigo: 1185, descripcion: "No Defino" },
  { subcodigo: 1186, descripcion: "No Defino" },
  { subcodigo: 1187, descripcion: "No Defino" },
  { subcodigo: 1188, descripcion: "No Defino" },
  { subcodigo: 1189, descripcion: "No Defino" },
  { subcodigo: 1190, descripcion: "No Defino" },
  { subcodigo: 1191, descripcion: "No Defino" },
  { subcodigo: 1192, descripcion: "No Defino" },
  { subcodigo: 1193, descripcion: "No Defino" },
  { subcodigo: 1194, descripcion: "No Defino" },
  { subcodigo: 1195, descripcion: "No Defino" },
  { subcodigo: 1196, descripcion: "No Defino" },
  { subcodigo: 1197, descripcion: "No Defino" },
  { subcodigo: 1198, descripcion: "No Defino" },
  { subcodigo: 1199, descripcion: "No Defino" },
  { subcodigo: 1200, descripcion: "No Defino" },
  { subcodigo: 1201, descripcion: "SACANDO CASING" },
  { subcodigo: 1202, descripcion: "ARMAR COLGADOR (LINER)" },
  { subcodigo: 1203, descripcion: "DESINSTALAR COLGADOR (LINER)" },
  {
    subcodigo: 1204,
    descripcion: "INSTALAR EQUIPO DE SUPERFICIE / HERRAMIENTAS",
  },
  {
    subcodigo: 1205,
    descripcion: "DESINSTALAR EQUIPO DE SUPERFICIE / HERRAMIENTAS",
  },
  { subcodigo: 1206, descripcion: "BAJAR CASING / LINER" },
  { subcodigo: 1207, descripcion: "SENTAR LINER" },
  { subcodigo: 1208, descripcion: "INSPECCIONANDO CASING" },
  { subcodigo: 1209, descripcion: "No Defino" },
  { subcodigo: 1210, descripcion: "No Defino" },
  { subcodigo: 1211, descripcion: "No Defino" },
  { subcodigo: 1212, descripcion: "No Defino" },
  { subcodigo: 1213, descripcion: "No Defino" },
  { subcodigo: 1214, descripcion: "INSTALAR / DESINSTALAR FLOWLINE" },
  { subcodigo: 1215, descripcion: "No Defino" },
  { subcodigo: 1216, descripcion: "No Defino" },
  { subcodigo: 1217, descripcion: "No Defino" },
  { subcodigo: 1218, descripcion: "No Defino" },
  { subcodigo: 1219, descripcion: "No Defino" },
  { subcodigo: 1220, descripcion: "No Defino" },
  { subcodigo: 1221, descripcion: "No Defino" },
  { subcodigo: 1222, descripcion: "No Defino" },
  { subcodigo: 1223, descripcion: "No Defino" },
  { subcodigo: 1224, descripcion: "No Defino" },
  { subcodigo: 1225, descripcion: "No Defino" },
  { subcodigo: 1226, descripcion: "No Defino" },
  { subcodigo: 1227, descripcion: "No Defino" },
  { subcodigo: 1228, descripcion: "No Defino" },
  { subcodigo: 1229, descripcion: "No Defino" },
  { subcodigo: 1230, descripcion: "No Defino" },
  { subcodigo: 1231, descripcion: "No Defino" },
  { subcodigo: 1232, descripcion: "No Defino" },
  { subcodigo: 1233, descripcion: "No Defino" },
  { subcodigo: 1234, descripcion: "No Defino" },
  { subcodigo: 1235, descripcion: "No Defino" },
  { subcodigo: 1236, descripcion: "No Defino" },
  { subcodigo: 1237, descripcion: "No Defino" },
  { subcodigo: 1238, descripcion: "No Defino" },
  { subcodigo: 1239, descripcion: "No Defino" },
  { subcodigo: 1240, descripcion: "No Defino" },
  { subcodigo: 1241, descripcion: "No Defino" },
  { subcodigo: 1242, descripcion: "No Defino" },
  { subcodigo: 1243, descripcion: "No Defino" },
  { subcodigo: 1244, descripcion: "No Defino" },
  { subcodigo: 1245, descripcion: "No Defino" },
  { subcodigo: 1246, descripcion: "No Defino" },
  { subcodigo: 1247, descripcion: "No Defino" },
  { subcodigo: 1248, descripcion: "No Defino" },
  { subcodigo: 1249, descripcion: "No Defino" },
  { subcodigo: 1250, descripcion: "No Defino" },
  { subcodigo: 1251, descripcion: "No Defino" },
  { subcodigo: 1252, descripcion: "No Defino" },
  { subcodigo: 1253, descripcion: "No Defino" },
  { subcodigo: 1254, descripcion: "No Defino" },
  { subcodigo: 1255, descripcion: "No Defino" },
  { subcodigo: 1256, descripcion: "No Defino" },
  { subcodigo: 1257, descripcion: "No Defino" },
  { subcodigo: 1258, descripcion: "No Defino" },
  { subcodigo: 1259, descripcion: "No Defino" },
  { subcodigo: 1260, descripcion: "No Defino" },
  { subcodigo: 1261, descripcion: "No Defino" },
  { subcodigo: 1262, descripcion: "No Defino" },
  { subcodigo: 1263, descripcion: "No Defino" },
  { subcodigo: 1264, descripcion: "No Defino" },
  { subcodigo: 1265, descripcion: "No Defino" },
  { subcodigo: 1266, descripcion: "No Defino" },
  { subcodigo: 1267, descripcion: "No Defino" },
  { subcodigo: 1268, descripcion: "No Defino" },
  { subcodigo: 1269, descripcion: "No Defino" },
  { subcodigo: 1270, descripcion: "No Defino" },
  { subcodigo: 1271, descripcion: "No Defino" },
  { subcodigo: 1272, descripcion: "No Defino" },
  { subcodigo: 1273, descripcion: "No Defino" },
  { subcodigo: 1274, descripcion: "No Defino" },
  { subcodigo: 1275, descripcion: "No Defino" },
  { subcodigo: 1276, descripcion: "No Defino" },
  { subcodigo: 1277, descripcion: "No Defino" },
  { subcodigo: 1278, descripcion: "No Defino" },
  { subcodigo: 1279, descripcion: "No Defino" },
  { subcodigo: 1280, descripcion: "No Defino" },
  { subcodigo: 1281, descripcion: "No Defino" },
  { subcodigo: 1282, descripcion: "No Defino" },
  { subcodigo: 1283, descripcion: "No Defino" },
  { subcodigo: 1284, descripcion: "No Defino" },
  { subcodigo: 1285, descripcion: "No Defino" },
  { subcodigo: 1286, descripcion: "No Defino" },
  { subcodigo: 1287, descripcion: "No Defino" },
  { subcodigo: 1288, descripcion: "No Defino" },
  { subcodigo: 1289, descripcion: "No Defino" },
  { subcodigo: 1290, descripcion: "No Defino" },
  { subcodigo: 1291, descripcion: "No Defino" },
  { subcodigo: 1292, descripcion: "No Defino" },
  { subcodigo: 1293, descripcion: "No Defino" },
  { subcodigo: 1294, descripcion: "No Defino" },
  { subcodigo: 1295, descripcion: "No Defino" },
  { subcodigo: 1296, descripcion: "No Defino" },
  { subcodigo: 1297, descripcion: "No Defino" },
  { subcodigo: 1298, descripcion: "No Defino" },
  { subcodigo: 1299, descripcion: "No Defino" },
  { subcodigo: 1300, descripcion: "No Defino" },
  { subcodigo: 1301, descripcion: "PARANDO TUBERIAS / CALIBRACION / MEDIDA" },
  { subcodigo: 1302, descripcion: "QUEBRANDO TUBERIAS" },
  {
    subcodigo: 1303,
    descripcion: "INSTALAR / EQUIPO DE SUPERFICIE / HERRAMIENTAS TALADRO",
  },
  {
    subcodigo: 1304,
    descripcion: "DESINSTALAR / EQUIPO DE SUPERFICIE / HERRAMIENTAS TALADRO",
  },
  { subcodigo: 1305, descripcion: "MOVIENDO HERRAMIENTAS / TUBERIAS" },
  { subcodigo: 1306, descripcion: "DRENANDO CONTRAPOZO" },
  { subcodigo: 1307, descripcion: "CORRER-CORTAR CABLE" },
  { subcodigo: 1308, descripcion: "RIG SERVICE" },
  { subcodigo: 1309, descripcion: "No Defino" },
  { subcodigo: 1310, descripcion: "No Defino" },
  { subcodigo: 1311, descripcion: "No Defino" },
  { subcodigo: 1312, descripcion: "No Defino" },
  { subcodigo: 1313, descripcion: "No Defino" },
  { subcodigo: 1314, descripcion: "No Defino" },
  { subcodigo: 1315, descripcion: "No Defino" },
  { subcodigo: 1316, descripcion: "No Defino" },
  { subcodigo: 1317, descripcion: "No Defino" },
  { subcodigo: 1318, descripcion: "No Defino" },
  { subcodigo: 1319, descripcion: "No Defino" },
  { subcodigo: 1320, descripcion: "No Defino" },
  { subcodigo: 1321, descripcion: "No Defino" },
  { subcodigo: 1322, descripcion: "No Defino" },
  { subcodigo: 1323, descripcion: "No Defino" },
  { subcodigo: 1324, descripcion: "No Defino" },
  { subcodigo: 1325, descripcion: "No Defino" },
  { subcodigo: 1326, descripcion: "No Defino" },
  { subcodigo: 1327, descripcion: "No Defino" },
  { subcodigo: 1328, descripcion: "No Defino" },
  { subcodigo: 1329, descripcion: "No Defino" },
  { subcodigo: 1330, descripcion: "No Defino" },
  { subcodigo: 1331, descripcion: "No Defino" },
  { subcodigo: 1332, descripcion: "No Defino" },
  { subcodigo: 1333, descripcion: "No Defino" },
  { subcodigo: 1334, descripcion: "No Defino" },
  { subcodigo: 1335, descripcion: "No Defino" },
  { subcodigo: 1336, descripcion: "No Defino" },
  { subcodigo: 1337, descripcion: "No Defino" },
  { subcodigo: 1338, descripcion: "No Defino" },
  { subcodigo: 1339, descripcion: "No Defino" },
  { subcodigo: 1340, descripcion: "No Defino" },
  { subcodigo: 1341, descripcion: "No Defino" },
  { subcodigo: 1342, descripcion: "No Defino" },
  { subcodigo: 1343, descripcion: "No Defino" },
  { subcodigo: 1344, descripcion: "No Defino" },
  { subcodigo: 1345, descripcion: "No Defino" },
  { subcodigo: 1346, descripcion: "No Defino" },
  { subcodigo: 1347, descripcion: "No Defino" },
  { subcodigo: 1348, descripcion: "No Defino" },
  { subcodigo: 1349, descripcion: "No Defino" },
  { subcodigo: 1350, descripcion: "No Defino" },
  { subcodigo: 1351, descripcion: "No Defino" },
  { subcodigo: 1352, descripcion: "No Defino" },
  { subcodigo: 1353, descripcion: "No Defino" },
  { subcodigo: 1354, descripcion: "No Defino" },
  { subcodigo: 1355, descripcion: "No Defino" },
  { subcodigo: 1356, descripcion: "No Defino" },
  { subcodigo: 1357, descripcion: "No Defino" },
  { subcodigo: 1358, descripcion: "No Defino" },
  { subcodigo: 1359, descripcion: "No Defino" },
  { subcodigo: 1360, descripcion: "No Defino" },
  { subcodigo: 1361, descripcion: "No Defino" },
  { subcodigo: 1362, descripcion: "No Defino" },
  { subcodigo: 1363, descripcion: "No Defino" },
  { subcodigo: 1364, descripcion: "No Defino" },
  { subcodigo: 1365, descripcion: "No Defino" },
  { subcodigo: 1366, descripcion: "No Defino" },
  { subcodigo: 1367, descripcion: "No Defino" },
  { subcodigo: 1368, descripcion: "No Defino" },
  { subcodigo: 1369, descripcion: "No Defino" },
  { subcodigo: 1370, descripcion: "No Defino" },
  { subcodigo: 1371, descripcion: "No Defino" },
  { subcodigo: 1372, descripcion: "No Defino" },
  { subcodigo: 1373, descripcion: "No Defino" },
  { subcodigo: 1374, descripcion: "No Defino" },
  { subcodigo: 1375, descripcion: "No Defino" },
  { subcodigo: 1376, descripcion: "No Defino" },
  { subcodigo: 1377, descripcion: "No Defino" },
  { subcodigo: 1378, descripcion: "No Defino" },
  { subcodigo: 1379, descripcion: "No Defino" },
  { subcodigo: 1380, descripcion: "No Defino" },
  { subcodigo: 1381, descripcion: "No Defino" },
  { subcodigo: 1382, descripcion: "No Defino" },
  { subcodigo: 1383, descripcion: "No Defino" },
  { subcodigo: 1384, descripcion: "No Defino" },
  { subcodigo: 1385, descripcion: "No Defino" },
  { subcodigo: 1386, descripcion: "No Defino" },
  { subcodigo: 1387, descripcion: "No Defino" },
  { subcodigo: 1388, descripcion: "No Defino" },
  { subcodigo: 1389, descripcion: "No Defino" },
  { subcodigo: 1390, descripcion: "No Defino" },
  { subcodigo: 1391, descripcion: "No Defino" },
  { subcodigo: 1392, descripcion: "No Defino" },
  { subcodigo: 1393, descripcion: "No Defino" },
  { subcodigo: 1394, descripcion: "No Defino" },
  { subcodigo: 1395, descripcion: "No Defino" },
  { subcodigo: 1396, descripcion: "No Defino" },
  { subcodigo: 1397, descripcion: "No Defino" },
  { subcodigo: 1398, descripcion: "No Defino" },
  { subcodigo: 1399, descripcion: "No Defino" },
  { subcodigo: 1400, descripcion: "No Defino" },
  { subcodigo: 1401, descripcion: "ARMANDO BHA" },
  { subcodigo: 1402, descripcion: "QUEBRANDO BHA" },
  {
    subcodigo: 1403,
    descripcion: "LEVANTANDO Y PROBANDO HERRAMIENTAS DIRECCIONALES",
  },
  { subcodigo: 1404, descripcion: "QUEBRANDO HERRAMIENTAS DIRECCIONALES" },
  { subcodigo: 1405, descripcion: "PERFORANDO DESLIZANDO" },
  { subcodigo: 1406, descripcion: "PERFORANDO ROTANDO CONVENCIONAL" },
  { subcodigo: 1407, descripcion: "PERFORANDO ROTANDO CON MOTOR" },
  { subcodigo: 1408, descripcion: "No Defino" },
  {
    subcodigo: 1409,
    descripcion: "PERFORANDO ROTANDO CON RSS (ROTARY STEERABLE SYSTEM)",
  },
  { subcodigo: 1410, descripcion: "MOLIENDO CEMENTO / PLUGS / EMPAQUES" },
  { subcodigo: 1411, descripcion: "ORIENTANDO TOOLFACE" },
  { subcodigo: 1412, descripcion: "No Defino" },
  { subcodigo: 1413, descripcion: "No Defino" },
  { subcodigo: 1414, descripcion: "No Defino" },
  { subcodigo: 1415, descripcion: "TRABAJANDO SARTA DE TUBERIA" },
  { subcodigo: 1416, descripcion: "No Defino" },
  { subcodigo: 1417, descripcion: "No Defino" },
  { subcodigo: 1418, descripcion: "No Defino" },
  { subcodigo: 1419, descripcion: "No Defino" },
  { subcodigo: 1420, descripcion: "No Defino" },
  { subcodigo: 1421, descripcion: "No Defino" },
  { subcodigo: 1422, descripcion: "No Defino" },
  { subcodigo: 1423, descripcion: "No Defino" },
  { subcodigo: 1424, descripcion: "No Defino" },
  { subcodigo: 1425, descripcion: "No Defino" },
  { subcodigo: 1426, descripcion: "No Defino" },
  { subcodigo: 1427, descripcion: "No Defino" },
  { subcodigo: 1428, descripcion: "No Defino" },
  { subcodigo: 1429, descripcion: "No Defino" },
  { subcodigo: 1430, descripcion: "No Defino" },
  { subcodigo: 1431, descripcion: "No Defino" },
  { subcodigo: 1432, descripcion: "No Defino" },
  { subcodigo: 1433, descripcion: "No Defino" },
  { subcodigo: 1434, descripcion: "No Defino" },
  { subcodigo: 1435, descripcion: "No Defino" },
  { subcodigo: 1436, descripcion: "No Defino" },
  { subcodigo: 1437, descripcion: "No Defino" },
  { subcodigo: 1438, descripcion: "No Defino" },
  { subcodigo: 1439, descripcion: "No Defino" },
  { subcodigo: 1440, descripcion: "No Defino" },
  { subcodigo: 1441, descripcion: "No Defino" },
  { subcodigo: 1442, descripcion: "No Defino" },
  { subcodigo: 1443, descripcion: "No Defino" },
  { subcodigo: 1444, descripcion: "No Defino" },
  { subcodigo: 1445, descripcion: "No Defino" },
  { subcodigo: 1446, descripcion: "No Defino" },
  { subcodigo: 1447, descripcion: "No Defino" },
  { subcodigo: 1448, descripcion: "No Defino" },
  { subcodigo: 1449, descripcion: "No Defino" },
  { subcodigo: 1450, descripcion: "No Defino" },
  { subcodigo: 1451, descripcion: "No Defino" },
  { subcodigo: 1452, descripcion: "No Defino" },
  { subcodigo: 1453, descripcion: "No Defino" },
  { subcodigo: 1454, descripcion: "No Defino" },
  { subcodigo: 1455, descripcion: "No Defino" },
  { subcodigo: 1456, descripcion: "No Defino" },
  { subcodigo: 1457, descripcion: "No Defino" },
  { subcodigo: 1458, descripcion: "No Defino" },
  { subcodigo: 1459, descripcion: "No Defino" },
  { subcodigo: 1460, descripcion: "No Defino" },
  { subcodigo: 1461, descripcion: "No Defino" },
  { subcodigo: 1462, descripcion: "No Defino" },
  { subcodigo: 1463, descripcion: "No Defino" },
  { subcodigo: 1464, descripcion: "No Defino" },
  { subcodigo: 1465, descripcion: "No Defino" },
  { subcodigo: 1466, descripcion: "No Defino" },
  { subcodigo: 1467, descripcion: "No Defino" },
  { subcodigo: 1468, descripcion: "No Defino" },
  { subcodigo: 1469, descripcion: "No Defino" },
  { subcodigo: 1470, descripcion: "No Defino" },
  { subcodigo: 1471, descripcion: "No Defino" },
  { subcodigo: 1472, descripcion: "No Defino" },
  { subcodigo: 1473, descripcion: "No Defino" },
  { subcodigo: 1474, descripcion: "No Defino" },
  { subcodigo: 1475, descripcion: "No Defino" },
  { subcodigo: 1476, descripcion: "No Defino" },
  { subcodigo: 1477, descripcion: "No Defino" },
  { subcodigo: 1478, descripcion: "No Defino" },
  { subcodigo: 1479, descripcion: "No Defino" },
  { subcodigo: 1480, descripcion: "No Defino" },
  { subcodigo: 1481, descripcion: "No Defino" },
  { subcodigo: 1482, descripcion: "No Defino" },
  { subcodigo: 1483, descripcion: "No Defino" },
  { subcodigo: 1484, descripcion: "No Defino" },
  { subcodigo: 1485, descripcion: "No Defino" },
  { subcodigo: 1486, descripcion: "No Defino" },
  { subcodigo: 1487, descripcion: "No Defino" },
  { subcodigo: 1488, descripcion: "No Defino" },
  { subcodigo: 1489, descripcion: "No Defino" },
  { subcodigo: 1490, descripcion: "No Defino" },
  { subcodigo: 1491, descripcion: "No Defino" },
  { subcodigo: 1492, descripcion: "No Defino" },
  { subcodigo: 1493, descripcion: "No Defino" },
  { subcodigo: 1494, descripcion: "No Defino" },
  { subcodigo: 1495, descripcion: "No Defino" },
  { subcodigo: 1496, descripcion: "No Defino" },
  { subcodigo: 1497, descripcion: "No Defino" },
  { subcodigo: 1498, descripcion: "No Defino" },
  { subcodigo: 1499, descripcion: "No Defino" },
  { subcodigo: 1500, descripcion: "No Defino" },
  { subcodigo: 1501, descripcion: "ACONDICIONAMIENTO DE LODO Y CIRCULACION" },
  { subcodigo: 1502, descripcion: "DESPLAZAMIENTO FLUIDOS" },
  {
    subcodigo: 1503,
    descripcion: "CIRCULANDO (HUECO A LIMPIO, PILDORAS, MUESTRAS)",
  },
  { subcodigo: 1504, descripcion: "No Defino" },
  { subcodigo: 1505, descripcion: "PERDIDA DE CIRCULACION" },
  { subcodigo: 1506, descripcion: "PREPARANDO FLUIDOS" },
  { subcodigo: 1507, descripcion: "PRUEBA DE INFLUJO / CHEQUEO DE POZO" },
  { subcodigo: 1508, descripcion: "MANTENIMIENTO AL SISTEMA DE CIRCULACION" },
  { subcodigo: 1509, descripcion: "No Defino" },
  { subcodigo: 1510, descripcion: "No Defino" },
  { subcodigo: 1511, descripcion: "No Defino" },
  { subcodigo: 1512, descripcion: "No Defino" },
  { subcodigo: 1513, descripcion: "No Defino" },
  { subcodigo: 1514, descripcion: "No Defino" },
  { subcodigo: 1515, descripcion: "No Defino" },
  { subcodigo: 1516, descripcion: "No Defino" },
  { subcodigo: 1517, descripcion: "No Defino" },
  { subcodigo: 1518, descripcion: "No Defino" },
  { subcodigo: 1519, descripcion: "No Defino" },
  { subcodigo: 1520, descripcion: "No Defino" },
  { subcodigo: 1521, descripcion: "No Defino" },
  { subcodigo: 1522, descripcion: "No Defino" },
  { subcodigo: 1523, descripcion: "No Defino" },
  { subcodigo: 1524, descripcion: "No Defino" },
  { subcodigo: 1525, descripcion: "No Defino" },
  { subcodigo: 1526, descripcion: "No Defino" },
  { subcodigo: 1527, descripcion: "No Defino" },
  { subcodigo: 1528, descripcion: "No Defino" },
  { subcodigo: 1529, descripcion: "No Defino" },
  { subcodigo: 1530, descripcion: "No Defino" },
  { subcodigo: 1531, descripcion: "No Defino" },
  { subcodigo: 1532, descripcion: "No Defino" },
  { subcodigo: 1533, descripcion: "No Defino" },
  { subcodigo: 1534, descripcion: "No Defino" },
  { subcodigo: 1535, descripcion: "No Defino" },
  { subcodigo: 1536, descripcion: "No Defino" },
  { subcodigo: 1537, descripcion: "No Defino" },
  { subcodigo: 1538, descripcion: "No Defino" },
  { subcodigo: 1539, descripcion: "No Defino" },
  { subcodigo: 1540, descripcion: "No Defino" },
  { subcodigo: 1541, descripcion: "No Defino" },
  { subcodigo: 1542, descripcion: "No Defino" },
  { subcodigo: 1543, descripcion: "No Defino" },
  { subcodigo: 1544, descripcion: "No Defino" },
  { subcodigo: 1545, descripcion: "No Defino" },
  { subcodigo: 1546, descripcion: "No Defino" },
  { subcodigo: 1547, descripcion: "No Defino" },
  { subcodigo: 1548, descripcion: "No Defino" },
  { subcodigo: 1549, descripcion: "No Defino" },
  { subcodigo: 1550, descripcion: "No Defino" },
  { subcodigo: 1551, descripcion: "No Defino" },
  { subcodigo: 1552, descripcion: "No Defino" },
  { subcodigo: 1553, descripcion: "No Defino" },
  { subcodigo: 1554, descripcion: "No Defino" },
  { subcodigo: 1555, descripcion: "No Defino" },
  { subcodigo: 1556, descripcion: "No Defino" },
  { subcodigo: 1557, descripcion: "No Defino" },
  { subcodigo: 1558, descripcion: "No Defino" },
  { subcodigo: 1559, descripcion: "No Defino" },
  { subcodigo: 1560, descripcion: "No Defino" },
  { subcodigo: 1561, descripcion: "No Defino" },
  { subcodigo: 1562, descripcion: "No Defino" },
  { subcodigo: 1563, descripcion: "No Defino" },
  { subcodigo: 1564, descripcion: "No Defino" },
  { subcodigo: 1565, descripcion: "No Defino" },
  { subcodigo: 1566, descripcion: "No Defino" },
  { subcodigo: 1567, descripcion: "No Defino" },
  { subcodigo: 1568, descripcion: "No Defino" },
  { subcodigo: 1569, descripcion: "No Defino" },
  { subcodigo: 1570, descripcion: "No Defino" },
  { subcodigo: 1571, descripcion: "No Defino" },
  { subcodigo: 1572, descripcion: "No Defino" },
  { subcodigo: 1573, descripcion: "No Defino" },
  { subcodigo: 1574, descripcion: "No Defino" },
  { subcodigo: 1575, descripcion: "No Defino" },
  { subcodigo: 1576, descripcion: "No Defino" },
  { subcodigo: 1577, descripcion: "No Defino" },
  { subcodigo: 1578, descripcion: "No Defino" },
  { subcodigo: 1579, descripcion: "No Defino" },
  { subcodigo: 1580, descripcion: "No Defino" },
  { subcodigo: 1581, descripcion: "No Defino" },
  { subcodigo: 1582, descripcion: "No Defino" },
  { subcodigo: 1583, descripcion: "No Defino" },
  { subcodigo: 1584, descripcion: "No Defino" },
  { subcodigo: 1585, descripcion: "No Defino" },
  { subcodigo: 1586, descripcion: "No Defino" },
  { subcodigo: 1587, descripcion: "No Defino" },
  { subcodigo: 1588, descripcion: "No Defino" },
  { subcodigo: 1589, descripcion: "No Defino" },
  { subcodigo: 1590, descripcion: "No Defino" },
  { subcodigo: 1591, descripcion: "No Defino" },
  { subcodigo: 1592, descripcion: "No Defino" },
  { subcodigo: 1593, descripcion: "No Defino" },
  { subcodigo: 1594, descripcion: "No Defino" },
  { subcodigo: 1595, descripcion: "No Defino" },
  { subcodigo: 1596, descripcion: "No Defino" },
  { subcodigo: 1597, descripcion: "No Defino" },
  { subcodigo: 1598, descripcion: "No Defino" },
  { subcodigo: 1599, descripcion: "No Defino" },
  { subcodigo: 1600, descripcion: "No Defino" },
  { subcodigo: 1601, descripcion: "ARMANDO BHA (PESCA)" },
  { subcodigo: 1602, descripcion: "QUEBRANDO BHA (PESCA)" },
  { subcodigo: 1603, descripcion: "No Defino" },
  {
    subcodigo: 1604,
    descripcion: "INSTALAR EQUIPO DE SUPERFICIE / HERRAMIENTAS DE PESCA",
  },
  {
    subcodigo: 1605,
    descripcion: "DESINSTALAR EQUIPO DE SUPERFICIE / HERRAMIENTAS DE PESCA",
  },
  { subcodigo: 1606, descripcion: "OPERACI�N STRING SHOT" },
  { subcodigo: 1607, descripcion: "PESCA DE TUBERIA / BHA" },
  {
    subcodigo: 1608,
    descripcion: "PESCANDO HERRAMIENTAS DE REGISTROS / CABLE",
  },
  { subcodigo: 1609, descripcion: "PESCANDO OTROS" },
  { subcodigo: 1610, descripcion: "PUNTO LIBRE O BACKOFF / TUBERIA" },
  { subcodigo: 1611, descripcion: "TRABAJANDO SARTA DE TUBERIA" },
  { subcodigo: 1612, descripcion: "OPERACIONES CON WASH PIPE (LAVANDO)" },
  { subcodigo: 1613, descripcion: "MOLIENDO" },
  { subcodigo: 1614, descripcion: "No Defino" },
  { subcodigo: 1615, descripcion: "No Defino" },
  { subcodigo: 1616, descripcion: "No Defino" },
  { subcodigo: 1617, descripcion: "No Defino" },
  { subcodigo: 1618, descripcion: "No Defino" },
  { subcodigo: 1619, descripcion: "No Defino" },
  { subcodigo: 1620, descripcion: "No Defino" },
  { subcodigo: 1621, descripcion: "No Defino" },
  { subcodigo: 1622, descripcion: "No Defino" },
  { subcodigo: 1623, descripcion: "No Defino" },
  { subcodigo: 1624, descripcion: "No Defino" },
  { subcodigo: 1625, descripcion: "No Defino" },
  { subcodigo: 1626, descripcion: "No Defino" },
  { subcodigo: 1627, descripcion: "No Defino" },
  { subcodigo: 1628, descripcion: "No Defino" },
  { subcodigo: 1629, descripcion: "No Defino" },
  { subcodigo: 1630, descripcion: "No Defino" },
  { subcodigo: 1631, descripcion: "No Defino" },
  { subcodigo: 1632, descripcion: "No Defino" },
  { subcodigo: 1633, descripcion: "No Defino" },
  { subcodigo: 1634, descripcion: "No Defino" },
  { subcodigo: 1635, descripcion: "No Defino" },
  { subcodigo: 1636, descripcion: "No Defino" },
  { subcodigo: 1637, descripcion: "No Defino" },
  { subcodigo: 1638, descripcion: "No Defino" },
  { subcodigo: 1639, descripcion: "No Defino" },
  { subcodigo: 1640, descripcion: "No Defino" },
  { subcodigo: 1641, descripcion: "No Defino" },
  { subcodigo: 1642, descripcion: "No Defino" },
  { subcodigo: 1643, descripcion: "No Defino" },
  { subcodigo: 1644, descripcion: "No Defino" },
  { subcodigo: 1645, descripcion: "No Defino" },
  { subcodigo: 1646, descripcion: "No Defino" },
  { subcodigo: 1647, descripcion: "No Defino" },
  { subcodigo: 1648, descripcion: "No Defino" },
  { subcodigo: 1649, descripcion: "No Defino" },
  { subcodigo: 1650, descripcion: "No Defino" },
  { subcodigo: 1651, descripcion: "No Defino" },
  { subcodigo: 1652, descripcion: "No Defino" },
  { subcodigo: 1653, descripcion: "No Defino" },
  { subcodigo: 1654, descripcion: "No Defino" },
  { subcodigo: 1655, descripcion: "No Defino" },
  { subcodigo: 1656, descripcion: "No Defino" },
  { subcodigo: 1657, descripcion: "No Defino" },
  { subcodigo: 1658, descripcion: "No Defino" },
  { subcodigo: 1659, descripcion: "No Defino" },
  { subcodigo: 1660, descripcion: "No Defino" },
  { subcodigo: 1661, descripcion: "No Defino" },
  { subcodigo: 1662, descripcion: "No Defino" },
  { subcodigo: 1663, descripcion: "No Defino" },
  { subcodigo: 1664, descripcion: "No Defino" },
  { subcodigo: 1665, descripcion: "No Defino" },
  { subcodigo: 1666, descripcion: "No Defino" },
  { subcodigo: 1667, descripcion: "No Defino" },
  { subcodigo: 1668, descripcion: "No Defino" },
  { subcodigo: 1669, descripcion: "No Defino" },
  { subcodigo: 1670, descripcion: "No Defino" },
  { subcodigo: 1671, descripcion: "No Defino" },
  { subcodigo: 1672, descripcion: "No Defino" },
  { subcodigo: 1673, descripcion: "No Defino" },
  { subcodigo: 1674, descripcion: "No Defino" },
  { subcodigo: 1675, descripcion: "No Defino" },
  { subcodigo: 1676, descripcion: "No Defino" },
  { subcodigo: 1677, descripcion: "No Defino" },
  { subcodigo: 1678, descripcion: "No Defino" },
  { subcodigo: 1679, descripcion: "No Defino" },
  { subcodigo: 1680, descripcion: "No Defino" },
  { subcodigo: 1681, descripcion: "No Defino" },
  { subcodigo: 1682, descripcion: "No Defino" },
  { subcodigo: 1683, descripcion: "No Defino" },
  { subcodigo: 1684, descripcion: "No Defino" },
  { subcodigo: 1685, descripcion: "No Defino" },
  { subcodigo: 1686, descripcion: "No Defino" },
  { subcodigo: 1687, descripcion: "No Defino" },
  { subcodigo: 1688, descripcion: "No Defino" },
  { subcodigo: 1689, descripcion: "No Defino" },
  { subcodigo: 1690, descripcion: "No Defino" },
  { subcodigo: 1691, descripcion: "No Defino" },
  { subcodigo: 1692, descripcion: "No Defino" },
  { subcodigo: 1693, descripcion: "No Defino" },
  { subcodigo: 1694, descripcion: "No Defino" },
  { subcodigo: 1695, descripcion: "No Defino" },
  { subcodigo: 1696, descripcion: "No Defino" },
  { subcodigo: 1697, descripcion: "No Defino" },
  { subcodigo: 1698, descripcion: "No Defino" },
  { subcodigo: 1699, descripcion: "No Defino" },
  { subcodigo: 1700, descripcion: "No Defino" },
  { subcodigo: 1701, descripcion: "CHARLA DE SEGURIDAD PREOPERACIONAL" },
  { subcodigo: 1702, descripcion: "No Defino" },
  { subcodigo: 1703, descripcion: "INVESTIGACION DE INCIDENTES" },
  { subcodigo: 1704, descripcion: "PARADA DE SEGURIDAD" },
  { subcodigo: 1705, descripcion: "REUNION NO PROGRAMADA" },
  { subcodigo: 1706, descripcion: "SIMULACRO" },
  { subcodigo: 1707, descripcion: "No Defino" },
  { subcodigo: 1708, descripcion: "No Defino" },
  { subcodigo: 1709, descripcion: "No Defino" },
  { subcodigo: 1710, descripcion: "No Defino" },
  { subcodigo: 1711, descripcion: "No Defino" },
  { subcodigo: 1712, descripcion: "No Defino" },
  { subcodigo: 1713, descripcion: "No Defino" },
  { subcodigo: 1714, descripcion: "No Defino" },
  { subcodigo: 1715, descripcion: "No Defino" },
  { subcodigo: 1716, descripcion: "No Defino" },
  { subcodigo: 1717, descripcion: "No Defino" },
  { subcodigo: 1718, descripcion: "No Defino" },
  { subcodigo: 1719, descripcion: "No Defino" },
  { subcodigo: 1720, descripcion: "No Defino" },
  { subcodigo: 1721, descripcion: "No Defino" },
  { subcodigo: 1722, descripcion: "No Defino" },
  { subcodigo: 1723, descripcion: "No Defino" },
  { subcodigo: 1724, descripcion: "No Defino" },
  { subcodigo: 1725, descripcion: "No Defino" },
  { subcodigo: 1726, descripcion: "No Defino" },
  { subcodigo: 1727, descripcion: "No Defino" },
  { subcodigo: 1728, descripcion: "No Defino" },
  { subcodigo: 1729, descripcion: "No Defino" },
  { subcodigo: 1730, descripcion: "No Defino" },
  { subcodigo: 1731, descripcion: "No Defino" },
  { subcodigo: 1732, descripcion: "No Defino" },
  { subcodigo: 1733, descripcion: "No Defino" },
  { subcodigo: 1734, descripcion: "No Defino" },
  { subcodigo: 1735, descripcion: "No Defino" },
  { subcodigo: 1736, descripcion: "No Defino" },
  { subcodigo: 1737, descripcion: "No Defino" },
  { subcodigo: 1738, descripcion: "No Defino" },
  { subcodigo: 1739, descripcion: "No Defino" },
  { subcodigo: 1740, descripcion: "No Defino" },
  { subcodigo: 1741, descripcion: "No Defino" },
  { subcodigo: 1742, descripcion: "No Defino" },
  { subcodigo: 1743, descripcion: "No Defino" },
  { subcodigo: 1744, descripcion: "No Defino" },
  { subcodigo: 1745, descripcion: "No Defino" },
  { subcodigo: 1746, descripcion: "No Defino" },
  { subcodigo: 1747, descripcion: "No Defino" },
  { subcodigo: 1748, descripcion: "No Defino" },
  { subcodigo: 1749, descripcion: "No Defino" },
  { subcodigo: 1750, descripcion: "No Defino" },
  { subcodigo: 1751, descripcion: "No Defino" },
  { subcodigo: 1752, descripcion: "No Defino" },
  { subcodigo: 1753, descripcion: "No Defino" },
  { subcodigo: 1754, descripcion: "No Defino" },
  { subcodigo: 1755, descripcion: "No Defino" },
  { subcodigo: 1756, descripcion: "No Defino" },
  { subcodigo: 1757, descripcion: "No Defino" },
  { subcodigo: 1758, descripcion: "No Defino" },
  { subcodigo: 1759, descripcion: "No Defino" },
  { subcodigo: 1760, descripcion: "No Defino" },
  { subcodigo: 1761, descripcion: "No Defino" },
  { subcodigo: 1762, descripcion: "No Defino" },
  { subcodigo: 1763, descripcion: "No Defino" },
  { subcodigo: 1764, descripcion: "No Defino" },
  { subcodigo: 1765, descripcion: "No Defino" },
  { subcodigo: 1766, descripcion: "No Defino" },
  { subcodigo: 1767, descripcion: "No Defino" },
  { subcodigo: 1768, descripcion: "No Defino" },
  { subcodigo: 1769, descripcion: "No Defino" },
  { subcodigo: 1770, descripcion: "No Defino" },
  { subcodigo: 1771, descripcion: "No Defino" },
  { subcodigo: 1772, descripcion: "No Defino" },
  { subcodigo: 1773, descripcion: "No Defino" },
  { subcodigo: 1774, descripcion: "No Defino" },
  { subcodigo: 1775, descripcion: "No Defino" },
  { subcodigo: 1776, descripcion: "No Defino" },
  { subcodigo: 1777, descripcion: "No Defino" },
  { subcodigo: 1778, descripcion: "No Defino" },
  { subcodigo: 1779, descripcion: "No Defino" },
  { subcodigo: 1780, descripcion: "No Defino" },
  { subcodigo: 1781, descripcion: "No Defino" },
  { subcodigo: 1782, descripcion: "No Defino" },
  { subcodigo: 1783, descripcion: "No Defino" },
  { subcodigo: 1784, descripcion: "No Defino" },
  { subcodigo: 1785, descripcion: "No Defino" },
  { subcodigo: 1786, descripcion: "No Defino" },
  { subcodigo: 1787, descripcion: "No Defino" },
  { subcodigo: 1788, descripcion: "No Defino" },
  { subcodigo: 1789, descripcion: "No Defino" },
  { subcodigo: 1790, descripcion: "No Defino" },
  { subcodigo: 1791, descripcion: "No Defino" },
  { subcodigo: 1792, descripcion: "No Defino" },
  { subcodigo: 1793, descripcion: "No Defino" },
  { subcodigo: 1794, descripcion: "No Defino" },
  { subcodigo: 1795, descripcion: "No Defino" },
  { subcodigo: 1796, descripcion: "No Defino" },
  { subcodigo: 1797, descripcion: "No Defino" },
  { subcodigo: 1798, descripcion: "No Defino" },
  { subcodigo: 1799, descripcion: "No Defino" },
  { subcodigo: 1800, descripcion: "No Defino" },
  { subcodigo: 1801, descripcion: "EVALUANDO" },
  {
    subcodigo: 1802,
    descripcion: "INSTALAR / DESINSTALAR EQUIPO DE SUPERFICIE / HERRAMIENTAS",
  },
  {
    subcodigo: 1803,
    descripcion: "DESINSTALAR EQUIPO DE SUPERFICIE / HERRAMIENTAS",
  },
  {
    subcodigo: 1804,
    descripcion: "TOMANDO REGISTROS EN HUECO ABIERTO CON WIRELINE",
  },
  { subcodigo: 1805, descripcion: "TOMANDO REGISTROS TLC EN HUECO ABIERTO" },
  {
    subcodigo: 1806,
    descripcion: "TOMANDO REGISTROS DE PRESION EN HUECO ABIERTO",
  },
  { subcodigo: 1807, descripcion: "TOMANDO REGISTROS DE PRESION CON TLC" },
  { subcodigo: 1808, descripcion: "TOMANDO REGISTROS CON DROPOFF" },
  { subcodigo: 1809, descripcion: "No Defino" },
  { subcodigo: 1810, descripcion: "TOMANDO REGISTROS EN HUECO REVESTIDO" },
  { subcodigo: 1811, descripcion: "BAJANDO HERRAMIENTAS OP LOGGING" },
  { subcodigo: 1812, descripcion: "POOH HERRAMIENTAS DE REGISTRO" },
  { subcodigo: 1813, descripcion: "No Defino" },
  { subcodigo: 1814, descripcion: "No Defino" },
  { subcodigo: 1815, descripcion: "No Defino" },
  { subcodigo: 1816, descripcion: "No Defino" },
  { subcodigo: 1817, descripcion: "No Defino" },
  { subcodigo: 1818, descripcion: "No Defino" },
  { subcodigo: 1819, descripcion: "No Defino" },
  { subcodigo: 1820, descripcion: "No Defino" },
  { subcodigo: 1821, descripcion: "No Defino" },
  { subcodigo: 1822, descripcion: "No Defino" },
  { subcodigo: 1823, descripcion: "No Defino" },
  { subcodigo: 1824, descripcion: "No Defino" },
  { subcodigo: 1825, descripcion: "No Defino" },
  { subcodigo: 1826, descripcion: "No Defino" },
  { subcodigo: 1827, descripcion: "No Defino" },
  { subcodigo: 1828, descripcion: "No Defino" },
  { subcodigo: 1829, descripcion: "No Defino" },
  { subcodigo: 1830, descripcion: "No Defino" },
  { subcodigo: 1831, descripcion: "No Defino" },
  { subcodigo: 1832, descripcion: "No Defino" },
  { subcodigo: 1833, descripcion: "No Defino" },
  { subcodigo: 1834, descripcion: "No Defino" },
  { subcodigo: 1835, descripcion: "No Defino" },
  { subcodigo: 1836, descripcion: "No Defino" },
  { subcodigo: 1837, descripcion: "No Defino" },
  { subcodigo: 1838, descripcion: "No Defino" },
  { subcodigo: 1839, descripcion: "No Defino" },
  { subcodigo: 1840, descripcion: "No Defino" },
  { subcodigo: 1841, descripcion: "No Defino" },
  { subcodigo: 1842, descripcion: "No Defino" },
  { subcodigo: 1843, descripcion: "No Defino" },
  { subcodigo: 1844, descripcion: "No Defino" },
  { subcodigo: 1845, descripcion: "No Defino" },
  { subcodigo: 1846, descripcion: "No Defino" },
  { subcodigo: 1847, descripcion: "No Defino" },
  { subcodigo: 1848, descripcion: "No Defino" },
  { subcodigo: 1849, descripcion: "No Defino" },
  { subcodigo: 1850, descripcion: "No Defino" },
  { subcodigo: 1851, descripcion: "No Defino" },
  { subcodigo: 1852, descripcion: "No Defino" },
  { subcodigo: 1853, descripcion: "No Defino" },
  { subcodigo: 1854, descripcion: "No Defino" },
  { subcodigo: 1855, descripcion: "No Defino" },
  { subcodigo: 1856, descripcion: "No Defino" },
  { subcodigo: 1857, descripcion: "No Defino" },
  { subcodigo: 1858, descripcion: "No Defino" },
  { subcodigo: 1859, descripcion: "No Defino" },
  { subcodigo: 1860, descripcion: "No Defino" },
  { subcodigo: 1861, descripcion: "No Defino" },
  { subcodigo: 1862, descripcion: "No Defino" },
  { subcodigo: 1863, descripcion: "No Defino" },
  { subcodigo: 1864, descripcion: "No Defino" },
  { subcodigo: 1865, descripcion: "No Defino" },
  { subcodigo: 1866, descripcion: "No Defino" },
  { subcodigo: 1867, descripcion: "No Defino" },
  { subcodigo: 1868, descripcion: "No Defino" },
  { subcodigo: 1869, descripcion: "No Defino" },
  { subcodigo: 1870, descripcion: "No Defino" },
  { subcodigo: 1871, descripcion: "No Defino" },
  { subcodigo: 1872, descripcion: "No Defino" },
  { subcodigo: 1873, descripcion: "No Defino" },
  { subcodigo: 1874, descripcion: "No Defino" },
  { subcodigo: 1875, descripcion: "No Defino" },
  { subcodigo: 1876, descripcion: "No Defino" },
  { subcodigo: 1877, descripcion: "No Defino" },
  { subcodigo: 1878, descripcion: "No Defino" },
  { subcodigo: 1879, descripcion: "No Defino" },
  { subcodigo: 1880, descripcion: "No Defino" },
  { subcodigo: 1881, descripcion: "No Defino" },
  { subcodigo: 1882, descripcion: "No Defino" },
  { subcodigo: 1883, descripcion: "No Defino" },
  { subcodigo: 1884, descripcion: "No Defino" },
  { subcodigo: 1885, descripcion: "No Defino" },
  { subcodigo: 1886, descripcion: "No Defino" },
  { subcodigo: 1887, descripcion: "No Defino" },
  { subcodigo: 1888, descripcion: "No Defino" },
  { subcodigo: 1889, descripcion: "No Defino" },
  { subcodigo: 1890, descripcion: "No Defino" },
  { subcodigo: 1891, descripcion: "No Defino" },
  { subcodigo: 1892, descripcion: "No Defino" },
  { subcodigo: 1893, descripcion: "No Defino" },
  { subcodigo: 1894, descripcion: "No Defino" },
  { subcodigo: 1895, descripcion: "No Defino" },
  { subcodigo: 1896, descripcion: "No Defino" },
  { subcodigo: 1897, descripcion: "No Defino" },
  { subcodigo: 1898, descripcion: "No Defino" },
  { subcodigo: 1899, descripcion: "No Defino" },
  { subcodigo: 1900, descripcion: "No Defino" },
  { subcodigo: 1901, descripcion: "No Defino" },
  { subcodigo: 1902, descripcion: "No Defino" },
  {
    subcodigo: 1903,
    descripcion: "ESPERANDO HERRAMIENTAS / EQUIPOS / MATERIALES",
  },
  { subcodigo: 1904, descripcion: "ESPERANDO ORDENES" },
  { subcodigo: 1905, descripcion: "ESPERANDO POR CLIMA" },
  { subcodigo: 1906, descripcion: "ESPERANDO POR ORDEN PUBLICO" },
  { subcodigo: 1907, descripcion: "FALLA EN EL EQUIPO DE FONDO" },
  { subcodigo: 1908, descripcion: "No Defino" },
  { subcodigo: 1909, descripcion: "No Defino" },
  { subcodigo: 1910, descripcion: "No Defino" },
  { subcodigo: 1911, descripcion: "No Defino" },
  {
    subcodigo: 1912,
    descripcion: "FALLA / REPARACION EQUIPOS / HERRAMIENTAS OTROS",
  },
  { subcodigo: 1913, descripcion: "No Defino" },
  { subcodigo: 1914, descripcion: "No Defino" },
  {
    subcodigo: 1915,
    descripcion: "FALLA / REPARACION EQUIPOS / HERRAMIENTAS REGISTROS",
  },
  {
    subcodigo: 1916,
    descripcion: "FALLA / REPARACION EQUIPOS / HERRAMIENTAS TORRE",
  },
  { subcodigo: 1917, descripcion: "No Defino" },
  { subcodigo: 1918, descripcion: "No Defino" },
  { subcodigo: 1919, descripcion: "No Defino" },
  { subcodigo: 1920, descripcion: "No Defino" },
  { subcodigo: 1921, descripcion: "No Defino" },
  { subcodigo: 1922, descripcion: "No Defino" },
  { subcodigo: 1923, descripcion: "No Defino" },
  { subcodigo: 1924, descripcion: "No Defino" },
  { subcodigo: 1925, descripcion: "No Defino" },
  { subcodigo: 1926, descripcion: "No Defino" },
  { subcodigo: 1927, descripcion: "No Defino" },
  { subcodigo: 1928, descripcion: "No Defino" },
  { subcodigo: 1929, descripcion: "No Defino" },
  { subcodigo: 1930, descripcion: "No Defino" },
  { subcodigo: 1931, descripcion: "No Defino" },
  { subcodigo: 1932, descripcion: "No Defino" },
  { subcodigo: 1933, descripcion: "No Defino" },
  { subcodigo: 1934, descripcion: "No Defino" },
  { subcodigo: 1935, descripcion: "No Defino" },
  { subcodigo: 1936, descripcion: "No Defino" },
  { subcodigo: 1937, descripcion: "No Defino" },
  { subcodigo: 1938, descripcion: "No Defino" },
  { subcodigo: 1939, descripcion: "No Defino" },
  { subcodigo: 1940, descripcion: "No Defino" },
  { subcodigo: 1941, descripcion: "No Defino" },
  { subcodigo: 1942, descripcion: "No Defino" },
  { subcodigo: 1943, descripcion: "No Defino" },
  { subcodigo: 1944, descripcion: "No Defino" },
  { subcodigo: 1945, descripcion: "No Defino" },
  { subcodigo: 1946, descripcion: "No Defino" },
  { subcodigo: 1947, descripcion: "No Defino" },
  { subcodigo: 1948, descripcion: "No Defino" },
  { subcodigo: 1949, descripcion: "No Defino" },
  { subcodigo: 1950, descripcion: "No Defino" },
  { subcodigo: 1951, descripcion: "No Defino" },
  { subcodigo: 1952, descripcion: "No Defino" },
  { subcodigo: 1953, descripcion: "No Defino" },
  { subcodigo: 1954, descripcion: "No Defino" },
  { subcodigo: 1955, descripcion: "No Defino" },
  { subcodigo: 1956, descripcion: "No Defino" },
  { subcodigo: 1957, descripcion: "No Defino" },
  { subcodigo: 1958, descripcion: "No Defino" },
  { subcodigo: 1959, descripcion: "No Defino" },
  { subcodigo: 1960, descripcion: "No Defino" },
  { subcodigo: 1961, descripcion: "No Defino" },
  { subcodigo: 1962, descripcion: "No Defino" },
  { subcodigo: 1963, descripcion: "No Defino" },
  { subcodigo: 1964, descripcion: "No Defino" },
  { subcodigo: 1965, descripcion: "No Defino" },
  { subcodigo: 1966, descripcion: "No Defino" },
  { subcodigo: 1967, descripcion: "No Defino" },
  { subcodigo: 1968, descripcion: "No Defino" },
  { subcodigo: 1969, descripcion: "No Defino" },
  { subcodigo: 1970, descripcion: "No Defino" },
  { subcodigo: 1971, descripcion: "No Defino" },
  { subcodigo: 1972, descripcion: "No Defino" },
  { subcodigo: 1973, descripcion: "No Defino" },
  { subcodigo: 1974, descripcion: "No Defino" },
  { subcodigo: 1975, descripcion: "No Defino" },
  { subcodigo: 1976, descripcion: "No Defino" },
  { subcodigo: 1977, descripcion: "No Defino" },
  { subcodigo: 1978, descripcion: "No Defino" },
  { subcodigo: 1979, descripcion: "No Defino" },
  { subcodigo: 1980, descripcion: "No Defino" },
  { subcodigo: 1981, descripcion: "No Defino" },
  { subcodigo: 1982, descripcion: "No Defino" },
  { subcodigo: 1983, descripcion: "No Defino" },
  { subcodigo: 1984, descripcion: "No Defino" },
  { subcodigo: 1985, descripcion: "No Defino" },
  { subcodigo: 1986, descripcion: "No Defino" },
  { subcodigo: 1987, descripcion: "No Defino" },
  { subcodigo: 1988, descripcion: "No Defino" },
  { subcodigo: 1989, descripcion: "No Defino" },
  { subcodigo: 1990, descripcion: "No Defino" },
  { subcodigo: 1991, descripcion: "No Defino" },
  { subcodigo: 1992, descripcion: "No Defino" },
  { subcodigo: 1993, descripcion: "No Defino" },
  { subcodigo: 1994, descripcion: "No Defino" },
  { subcodigo: 1995, descripcion: "No Defino" },
  { subcodigo: 1996, descripcion: "No Defino" },
  { subcodigo: 1997, descripcion: "No Defino" },
  { subcodigo: 1998, descripcion: "No Defino" },
  { subcodigo: 1999, descripcion: "No Defino" },
  { subcodigo: 2000, descripcion: "No Defino" },
  {
    subcodigo: 2001,
    descripcion: "INSTALAR EQUIPOS PARA PRUEBAS DE PRESION / HERRAMIENTAS",
  },
  {
    subcodigo: 2002,
    descripcion: "DESINSTALAR EQUIPOS PARA PRUEBAS DE PRESION / HERRAMIENTAS",
  },
  { subcodigo: 2003, descripcion: "PRUEBA CASING / LINNER / TUBING" },
  { subcodigo: 2004, descripcion: "PRUEBA DE INTEGRIDAD DE FORMACION" },
  { subcodigo: 2005, descripcion: "PRUEBA DE LINEAS DE SUPERFICIE" },
  { subcodigo: 2006, descripcion: "PRUEBA DE PRESION DE TUBERIA (INTEGRIDAD)" },
  { subcodigo: 2007, descripcion: "No Defino" },
  { subcodigo: 2008, descripcion: "No Defino" },
  { subcodigo: 2009, descripcion: "No Defino" },
  { subcodigo: 2010, descripcion: "No Defino" },
  { subcodigo: 2011, descripcion: "No Defino" },
  { subcodigo: 2012, descripcion: "No Defino" },
  { subcodigo: 2013, descripcion: "No Defino" },
  { subcodigo: 2014, descripcion: "No Defino" },
  { subcodigo: 2015, descripcion: "No Defino" },
  { subcodigo: 2016, descripcion: "No Defino" },
  { subcodigo: 2017, descripcion: "No Defino" },
  { subcodigo: 2018, descripcion: "No Defino" },
  { subcodigo: 2019, descripcion: "No Defino" },
  { subcodigo: 2020, descripcion: "No Defino" },
  { subcodigo: 2021, descripcion: "No Defino" },
  { subcodigo: 2022, descripcion: "No Defino" },
  { subcodigo: 2023, descripcion: "No Defino" },
  { subcodigo: 2024, descripcion: "No Defino" },
  { subcodigo: 2025, descripcion: "No Defino" },
  { subcodigo: 2026, descripcion: "No Defino" },
  { subcodigo: 2027, descripcion: "No Defino" },
  { subcodigo: 2028, descripcion: "No Defino" },
  { subcodigo: 2029, descripcion: "No Defino" },
  { subcodigo: 2030, descripcion: "No Defino" },
  { subcodigo: 2031, descripcion: "No Defino" },
  { subcodigo: 2032, descripcion: "No Defino" },
  { subcodigo: 2033, descripcion: "No Defino" },
  { subcodigo: 2034, descripcion: "No Defino" },
  { subcodigo: 2035, descripcion: "No Defino" },
  { subcodigo: 2036, descripcion: "No Defino" },
  { subcodigo: 2037, descripcion: "No Defino" },
  { subcodigo: 2038, descripcion: "No Defino" },
  { subcodigo: 2039, descripcion: "No Defino" },
  { subcodigo: 2040, descripcion: "No Defino" },
  { subcodigo: 2041, descripcion: "No Defino" },
  { subcodigo: 2042, descripcion: "No Defino" },
  { subcodigo: 2043, descripcion: "No Defino" },
  { subcodigo: 2044, descripcion: "No Defino" },
  { subcodigo: 2045, descripcion: "No Defino" },
  { subcodigo: 2046, descripcion: "No Defino" },
  { subcodigo: 2047, descripcion: "No Defino" },
  { subcodigo: 2048, descripcion: "No Defino" },
  { subcodigo: 2049, descripcion: "No Defino" },
  { subcodigo: 2050, descripcion: "No Defino" },
  { subcodigo: 2051, descripcion: "No Defino" },
  { subcodigo: 2052, descripcion: "No Defino" },
  { subcodigo: 2053, descripcion: "No Defino" },
  { subcodigo: 2054, descripcion: "No Defino" },
  { subcodigo: 2055, descripcion: "No Defino" },
  { subcodigo: 2056, descripcion: "No Defino" },
  { subcodigo: 2057, descripcion: "No Defino" },
  { subcodigo: 2058, descripcion: "No Defino" },
  { subcodigo: 2059, descripcion: "No Defino" },
  { subcodigo: 2060, descripcion: "No Defino" },
  { subcodigo: 2061, descripcion: "No Defino" },
  { subcodigo: 2062, descripcion: "No Defino" },
  { subcodigo: 2063, descripcion: "No Defino" },
  { subcodigo: 2064, descripcion: "No Defino" },
  { subcodigo: 2065, descripcion: "No Defino" },
  { subcodigo: 2066, descripcion: "No Defino" },
  { subcodigo: 2067, descripcion: "No Defino" },
  { subcodigo: 2068, descripcion: "No Defino" },
  { subcodigo: 2069, descripcion: "No Defino" },
  { subcodigo: 2070, descripcion: "No Defino" },
  { subcodigo: 2071, descripcion: "No Defino" },
  { subcodigo: 2072, descripcion: "No Defino" },
  { subcodigo: 2073, descripcion: "No Defino" },
  { subcodigo: 2074, descripcion: "No Defino" },
  { subcodigo: 2075, descripcion: "No Defino" },
  { subcodigo: 2076, descripcion: "No Defino" },
  { subcodigo: 2077, descripcion: "No Defino" },
  { subcodigo: 2078, descripcion: "No Defino" },
  { subcodigo: 2079, descripcion: "No Defino" },
  { subcodigo: 2080, descripcion: "No Defino" },
  { subcodigo: 2081, descripcion: "No Defino" },
  { subcodigo: 2082, descripcion: "No Defino" },
  { subcodigo: 2083, descripcion: "No Defino" },
  { subcodigo: 2084, descripcion: "No Defino" },
  { subcodigo: 2085, descripcion: "No Defino" },
  { subcodigo: 2086, descripcion: "No Defino" },
  { subcodigo: 2087, descripcion: "No Defino" },
  { subcodigo: 2088, descripcion: "No Defino" },
  { subcodigo: 2089, descripcion: "No Defino" },
  { subcodigo: 2090, descripcion: "No Defino" },
  { subcodigo: 2091, descripcion: "No Defino" },
  { subcodigo: 2092, descripcion: "No Defino" },
  { subcodigo: 2093, descripcion: "No Defino" },
  { subcodigo: 2094, descripcion: "No Defino" },
  { subcodigo: 2095, descripcion: "No Defino" },
  { subcodigo: 2096, descripcion: "No Defino" },
  { subcodigo: 2097, descripcion: "No Defino" },
  { subcodigo: 2098, descripcion: "No Defino" },
  { subcodigo: 2099, descripcion: "No Defino" },
  { subcodigo: 2100, descripcion: "No Defino" },
  {
    subcodigo: 2101,
    descripcion: "INSTALAR EQUIPO DE CEMENTACION / HERRAMIENTAS",
  },
  {
    subcodigo: 2102,
    descripcion: "DESINSTALAR EQUIPO DE CEMENTACION / HERRAMIENTAS",
  },
  { subcodigo: 2103, descripcion: "BALANCEANDO TAPON DE CEMENTO" },
  { subcodigo: 2104, descripcion: "CEMENTACION PRIMARIA" },
  { subcodigo: 2105, descripcion: "CEMENTACION REMEDIAL" },
  { subcodigo: 2106, descripcion: "ESPERANDO FRAGUE" },
  { subcodigo: 2107, descripcion: "PRUEBA DE INTEGRIDAD CEMENTO" },
  { subcodigo: 2108, descripcion: "No Defino" },
  { subcodigo: 2109, descripcion: "No Defino" },
  { subcodigo: 2110, descripcion: "No Defino" },
  { subcodigo: 2111, descripcion: "No Defino" },
  { subcodigo: 2112, descripcion: "No Defino" },
  { subcodigo: 2113, descripcion: "No Defino" },
  { subcodigo: 2114, descripcion: "No Defino" },
  { subcodigo: 2115, descripcion: "No Defino" },
  { subcodigo: 2116, descripcion: "No Defino" },
  { subcodigo: 2117, descripcion: "No Defino" },
  { subcodigo: 2118, descripcion: "No Defino" },
  { subcodigo: 2119, descripcion: "No Defino" },
  { subcodigo: 2120, descripcion: "No Defino" },
  { subcodigo: 2121, descripcion: "No Defino" },
  { subcodigo: 2122, descripcion: "No Defino" },
  { subcodigo: 2123, descripcion: "No Defino" },
  { subcodigo: 2124, descripcion: "No Defino" },
  { subcodigo: 2125, descripcion: "No Defino" },
  { subcodigo: 2126, descripcion: "No Defino" },
  { subcodigo: 2127, descripcion: "No Defino" },
  { subcodigo: 2128, descripcion: "No Defino" },
  { subcodigo: 2129, descripcion: "No Defino" },
  { subcodigo: 2130, descripcion: "No Defino" },
  { subcodigo: 2131, descripcion: "No Defino" },
  { subcodigo: 2132, descripcion: "No Defino" },
  { subcodigo: 2133, descripcion: "No Defino" },
  { subcodigo: 2134, descripcion: "No Defino" },
  { subcodigo: 2135, descripcion: "No Defino" },
  { subcodigo: 2136, descripcion: "No Defino" },
  { subcodigo: 2137, descripcion: "No Defino" },
  { subcodigo: 2138, descripcion: "No Defino" },
  { subcodigo: 2139, descripcion: "No Defino" },
  { subcodigo: 2140, descripcion: "No Defino" },
  { subcodigo: 2141, descripcion: "No Defino" },
  { subcodigo: 2142, descripcion: "No Defino" },
  { subcodigo: 2143, descripcion: "No Defino" },
  { subcodigo: 2144, descripcion: "No Defino" },
  { subcodigo: 2145, descripcion: "No Defino" },
  { subcodigo: 2146, descripcion: "No Defino" },
  { subcodigo: 2147, descripcion: "No Defino" },
  { subcodigo: 2148, descripcion: "No Defino" },
  { subcodigo: 2149, descripcion: "No Defino" },
  { subcodigo: 2150, descripcion: "No Defino" },
  { subcodigo: 2151, descripcion: "No Defino" },
  { subcodigo: 2152, descripcion: "No Defino" },
  { subcodigo: 2153, descripcion: "No Defino" },
  { subcodigo: 2154, descripcion: "No Defino" },
  { subcodigo: 2155, descripcion: "No Defino" },
  { subcodigo: 2156, descripcion: "No Defino" },
  { subcodigo: 2157, descripcion: "No Defino" },
  { subcodigo: 2158, descripcion: "No Defino" },
  { subcodigo: 2159, descripcion: "No Defino" },
  { subcodigo: 2160, descripcion: "No Defino" },
  { subcodigo: 2161, descripcion: "No Defino" },
  { subcodigo: 2162, descripcion: "No Defino" },
  { subcodigo: 2163, descripcion: "No Defino" },
  { subcodigo: 2164, descripcion: "No Defino" },
  { subcodigo: 2165, descripcion: "No Defino" },
  { subcodigo: 2166, descripcion: "No Defino" },
  { subcodigo: 2167, descripcion: "No Defino" },
  { subcodigo: 2168, descripcion: "No Defino" },
  { subcodigo: 2169, descripcion: "No Defino" },
  { subcodigo: 2170, descripcion: "No Defino" },
  { subcodigo: 2171, descripcion: "No Defino" },
  { subcodigo: 2172, descripcion: "No Defino" },
  { subcodigo: 2173, descripcion: "No Defino" },
  { subcodigo: 2174, descripcion: "No Defino" },
  { subcodigo: 2175, descripcion: "No Defino" },
  { subcodigo: 2176, descripcion: "No Defino" },
  { subcodigo: 2177, descripcion: "No Defino" },
  { subcodigo: 2178, descripcion: "No Defino" },
  { subcodigo: 2179, descripcion: "No Defino" },
  { subcodigo: 2180, descripcion: "No Defino" },
  { subcodigo: 2181, descripcion: "No Defino" },
  { subcodigo: 2182, descripcion: "No Defino" },
  { subcodigo: 2183, descripcion: "No Defino" },
  { subcodigo: 2184, descripcion: "No Defino" },
  { subcodigo: 2185, descripcion: "No Defino" },
  { subcodigo: 2186, descripcion: "No Defino" },
  { subcodigo: 2187, descripcion: "No Defino" },
  { subcodigo: 2188, descripcion: "No Defino" },
  { subcodigo: 2189, descripcion: "No Defino" },
  { subcodigo: 2190, descripcion: "No Defino" },
  { subcodigo: 2191, descripcion: "No Defino" },
  { subcodigo: 2192, descripcion: "No Defino" },
  { subcodigo: 2193, descripcion: "No Defino" },
  { subcodigo: 2194, descripcion: "No Defino" },
  { subcodigo: 2195, descripcion: "No Defino" },
  { subcodigo: 2196, descripcion: "No Defino" },
  { subcodigo: 2197, descripcion: "No Defino" },
  { subcodigo: 2198, descripcion: "No Defino" },
  { subcodigo: 2199, descripcion: "No Defino" },
  { subcodigo: 2200, descripcion: "No Defino" },
  { subcodigo: 2201, descripcion: "No Defino" },
  { subcodigo: 2202, descripcion: "No Defino" },
  { subcodigo: 2203, descripcion: "No Defino" },
  { subcodigo: 2204, descripcion: "No Defino" },
  { subcodigo: 2205, descripcion: "No Defino" },
  { subcodigo: 2206, descripcion: "No Defino" },
  { subcodigo: 2207, descripcion: "No Defino" },
  { subcodigo: 2208, descripcion: "No Defino" },
  { subcodigo: 2209, descripcion: "No Defino" },
  { subcodigo: 2210, descripcion: "No Defino" },
  { subcodigo: 2211, descripcion: "No Defino" },
  { subcodigo: 2212, descripcion: "No Defino" },
  { subcodigo: 2213, descripcion: "No Defino" },
  { subcodigo: 2214, descripcion: "No Defino" },
  { subcodigo: 2215, descripcion: "No Defino" },
  { subcodigo: 2216, descripcion: "No Defino" },
  { subcodigo: 2217, descripcion: "No Defino" },
  { subcodigo: 2218, descripcion: "No Defino" },
  { subcodigo: 2219, descripcion: "No Defino" },
  { subcodigo: 2220, descripcion: "No Defino" },
  { subcodigo: 2221, descripcion: "No Defino" },
  { subcodigo: 2222, descripcion: "No Defino" },
  { subcodigo: 2223, descripcion: "No Defino" },
  { subcodigo: 2224, descripcion: "No Defino" },
  { subcodigo: 2225, descripcion: "No Defino" },
  { subcodigo: 2226, descripcion: "No Defino" },
  { subcodigo: 2227, descripcion: "No Defino" },
  { subcodigo: 2228, descripcion: "No Defino" },
  { subcodigo: 2229, descripcion: "No Defino" },
  { subcodigo: 2230, descripcion: "No Defino" },
  { subcodigo: 2231, descripcion: "No Defino" },
  { subcodigo: 2232, descripcion: "No Defino" },
  { subcodigo: 2233, descripcion: "No Defino" },
  { subcodigo: 2234, descripcion: "No Defino" },
  { subcodigo: 2235, descripcion: "No Defino" },
  { subcodigo: 2236, descripcion: "No Defino" },
  { subcodigo: 2237, descripcion: "No Defino" },
  { subcodigo: 2238, descripcion: "No Defino" },
  { subcodigo: 2239, descripcion: "No Defino" },
  { subcodigo: 2240, descripcion: "No Defino" },
  { subcodigo: 2241, descripcion: "No Defino" },
  { subcodigo: 2242, descripcion: "No Defino" },
  { subcodigo: 2243, descripcion: "No Defino" },
  { subcodigo: 2244, descripcion: "No Defino" },
  { subcodigo: 2245, descripcion: "No Defino" },
  { subcodigo: 2246, descripcion: "No Defino" },
  { subcodigo: 2247, descripcion: "No Defino" },
  { subcodigo: 2248, descripcion: "No Defino" },
  { subcodigo: 2249, descripcion: "No Defino" },
  { subcodigo: 2250, descripcion: "No Defino" },
  { subcodigo: 2251, descripcion: "No Defino" },
  { subcodigo: 2252, descripcion: "No Defino" },
  { subcodigo: 2253, descripcion: "No Defino" },
  { subcodigo: 2254, descripcion: "No Defino" },
  { subcodigo: 2255, descripcion: "No Defino" },
  { subcodigo: 2256, descripcion: "No Defino" },
  { subcodigo: 2257, descripcion: "No Defino" },
  { subcodigo: 2258, descripcion: "No Defino" },
  { subcodigo: 2259, descripcion: "No Defino" },
  { subcodigo: 2260, descripcion: "No Defino" },
  { subcodigo: 2261, descripcion: "No Defino" },
  { subcodigo: 2262, descripcion: "No Defino" },
  { subcodigo: 2263, descripcion: "No Defino" },
  { subcodigo: 2264, descripcion: "No Defino" },
  { subcodigo: 2265, descripcion: "No Defino" },
  { subcodigo: 2266, descripcion: "No Defino" },
  { subcodigo: 2267, descripcion: "No Defino" },
  { subcodigo: 2268, descripcion: "No Defino" },
  { subcodigo: 2269, descripcion: "No Defino" },
  { subcodigo: 2270, descripcion: "No Defino" },
  { subcodigo: 2271, descripcion: "No Defino" },
  { subcodigo: 2272, descripcion: "No Defino" },
  { subcodigo: 2273, descripcion: "No Defino" },
  { subcodigo: 2274, descripcion: "No Defino" },
  { subcodigo: 2275, descripcion: "No Defino" },
  { subcodigo: 2276, descripcion: "No Defino" },
  { subcodigo: 2277, descripcion: "No Defino" },
  { subcodigo: 2278, descripcion: "No Defino" },
  { subcodigo: 2279, descripcion: "No Defino" },
  { subcodigo: 2280, descripcion: "No Defino" },
  { subcodigo: 2281, descripcion: "No Defino" },
  { subcodigo: 2282, descripcion: "No Defino" },
  { subcodigo: 2283, descripcion: "No Defino" },
  { subcodigo: 2284, descripcion: "No Defino" },
  { subcodigo: 2285, descripcion: "No Defino" },
  { subcodigo: 2286, descripcion: "No Defino" },
  { subcodigo: 2287, descripcion: "No Defino" },
  { subcodigo: 2288, descripcion: "No Defino" },
  { subcodigo: 2289, descripcion: "No Defino" },
  { subcodigo: 2290, descripcion: "No Defino" },
  { subcodigo: 2291, descripcion: "No Defino" },
  { subcodigo: 2292, descripcion: "No Defino" },
  { subcodigo: 2293, descripcion: "No Defino" },
  { subcodigo: 2294, descripcion: "No Defino" },
  { subcodigo: 2295, descripcion: "No Defino" },
  { subcodigo: 2296, descripcion: "No Defino" },
  { subcodigo: 2297, descripcion: "No Defino" },
  { subcodigo: 2298, descripcion: "No Defino" },
  { subcodigo: 2299, descripcion: "No Defino" },
  { subcodigo: 2300, descripcion: "No Defino" },
  { subcodigo: 2301, descripcion: "No Defino" },
  { subcodigo: 2302, descripcion: "No Defino" },
  { subcodigo: 2303, descripcion: "No Defino" },
  { subcodigo: 2304, descripcion: "No Defino" },
  { subcodigo: 2305, descripcion: "No Defino" },
  { subcodigo: 2306, descripcion: "No Defino" },
  { subcodigo: 2307, descripcion: "No Defino" },
  { subcodigo: 2308, descripcion: "No Defino" },
  { subcodigo: 2309, descripcion: "No Defino" },
  { subcodigo: 2310, descripcion: "No Defino" },
  { subcodigo: 2311, descripcion: "No Defino" },
  { subcodigo: 2312, descripcion: "No Defino" },
  { subcodigo: 2313, descripcion: "No Defino" },
  { subcodigo: 2314, descripcion: "No Defino" },
  { subcodigo: 2315, descripcion: "No Defino" },
  { subcodigo: 2316, descripcion: "No Defino" },
  { subcodigo: 2317, descripcion: "No Defino" },
  { subcodigo: 2318, descripcion: "No Defino" },
  { subcodigo: 2319, descripcion: "No Defino" },
  { subcodigo: 2320, descripcion: "No Defino" },
  { subcodigo: 2321, descripcion: "No Defino" },
  { subcodigo: 2322, descripcion: "No Defino" },
  { subcodigo: 2323, descripcion: "No Defino" },
  { subcodigo: 2324, descripcion: "No Defino" },
  { subcodigo: 2325, descripcion: "No Defino" },
  { subcodigo: 2326, descripcion: "No Defino" },
  { subcodigo: 2327, descripcion: "No Defino" },
  { subcodigo: 2328, descripcion: "No Defino" },
  { subcodigo: 2329, descripcion: "No Defino" },
  { subcodigo: 2330, descripcion: "No Defino" },
  { subcodigo: 2331, descripcion: "No Defino" },
  { subcodigo: 2332, descripcion: "No Defino" },
  { subcodigo: 2333, descripcion: "No Defino" },
  { subcodigo: 2334, descripcion: "No Defino" },
  { subcodigo: 2335, descripcion: "No Defino" },
  { subcodigo: 2336, descripcion: "No Defino" },
  { subcodigo: 2337, descripcion: "No Defino" },
  { subcodigo: 2338, descripcion: "No Defino" },
  { subcodigo: 2339, descripcion: "No Defino" },
  { subcodigo: 2340, descripcion: "No Defino" },
  { subcodigo: 2341, descripcion: "No Defino" },
  { subcodigo: 2342, descripcion: "No Defino" },
  { subcodigo: 2343, descripcion: "No Defino" },
  { subcodigo: 2344, descripcion: "No Defino" },
  { subcodigo: 2345, descripcion: "No Defino" },
  { subcodigo: 2346, descripcion: "No Defino" },
  { subcodigo: 2347, descripcion: "No Defino" },
  { subcodigo: 2348, descripcion: "No Defino" },
  { subcodigo: 2349, descripcion: "No Defino" },
  { subcodigo: 2350, descripcion: "No Defino" },
  { subcodigo: 2351, descripcion: "No Defino" },
  { subcodigo: 2352, descripcion: "No Defino" },
  { subcodigo: 2353, descripcion: "No Defino" },
  { subcodigo: 2354, descripcion: "No Defino" },
  { subcodigo: 2355, descripcion: "No Defino" },
  { subcodigo: 2356, descripcion: "No Defino" },
  { subcodigo: 2357, descripcion: "No Defino" },
  { subcodigo: 2358, descripcion: "No Defino" },
  { subcodigo: 2359, descripcion: "No Defino" },
  { subcodigo: 2360, descripcion: "No Defino" },
  { subcodigo: 2361, descripcion: "No Defino" },
  { subcodigo: 2362, descripcion: "No Defino" },
  { subcodigo: 2363, descripcion: "No Defino" },
  { subcodigo: 2364, descripcion: "No Defino" },
  { subcodigo: 2365, descripcion: "No Defino" },
  { subcodigo: 2366, descripcion: "No Defino" },
  { subcodigo: 2367, descripcion: "No Defino" },
  { subcodigo: 2368, descripcion: "No Defino" },
  { subcodigo: 2369, descripcion: "No Defino" },
  { subcodigo: 2370, descripcion: "No Defino" },
  { subcodigo: 2371, descripcion: "No Defino" },
  { subcodigo: 2372, descripcion: "No Defino" },
  { subcodigo: 2373, descripcion: "No Defino" },
  { subcodigo: 2374, descripcion: "No Defino" },
  { subcodigo: 2375, descripcion: "No Defino" },
  { subcodigo: 2376, descripcion: "No Defino" },
  { subcodigo: 2377, descripcion: "No Defino" },
  { subcodigo: 2378, descripcion: "No Defino" },
  { subcodigo: 2379, descripcion: "No Defino" },
  { subcodigo: 2380, descripcion: "No Defino" },
  { subcodigo: 2381, descripcion: "No Defino" },
  { subcodigo: 2382, descripcion: "No Defino" },
  { subcodigo: 2383, descripcion: "No Defino" },
  { subcodigo: 2384, descripcion: "No Defino" },
  { subcodigo: 2385, descripcion: "No Defino" },
  { subcodigo: 2386, descripcion: "No Defino" },
  { subcodigo: 2387, descripcion: "No Defino" },
  { subcodigo: 2388, descripcion: "No Defino" },
  { subcodigo: 2389, descripcion: "No Defino" },
  { subcodigo: 2390, descripcion: "No Defino" },
  { subcodigo: 2391, descripcion: "No Defino" },
  { subcodigo: 2392, descripcion: "No Defino" },
  { subcodigo: 2393, descripcion: "No Defino" },
  { subcodigo: 2394, descripcion: "No Defino" },
  { subcodigo: 2395, descripcion: "No Defino" },
  { subcodigo: 2396, descripcion: "No Defino" },
  { subcodigo: 2397, descripcion: "No Defino" },
  { subcodigo: 2398, descripcion: "No Defino" },
  { subcodigo: 2399, descripcion: "No Defino" },
  { subcodigo: 2400, descripcion: "No Defino" },
  { subcodigo: 2401, descripcion: "ABRIENDO VENTANA" },
  { subcodigo: 2402, descripcion: "No Defino" },
  { subcodigo: 2403, descripcion: "No Defino" },
  { subcodigo: 2404, descripcion: "No Defino" },
  { subcodigo: 2405, descripcion: "No Defino" },
  { subcodigo: 2406, descripcion: "No Defino" },
  { subcodigo: 2407, descripcion: "No Defino" },
  { subcodigo: 2408, descripcion: "No Defino" },
  { subcodigo: 2409, descripcion: "No Defino" },
  { subcodigo: 2410, descripcion: "No Defino" },
  { subcodigo: 2411, descripcion: "No Defino" },
  { subcodigo: 2412, descripcion: "No Defino" },
  { subcodigo: 2413, descripcion: "No Defino" },
  { subcodigo: 2414, descripcion: "No Defino" },
  { subcodigo: 2415, descripcion: "No Defino" },
  { subcodigo: 2416, descripcion: "No Defino" },
  { subcodigo: 2417, descripcion: "No Defino" },
  { subcodigo: 2418, descripcion: "No Defino" },
  { subcodigo: 2419, descripcion: "No Defino" },
  { subcodigo: 2420, descripcion: "No Defino" },
  { subcodigo: 2421, descripcion: "No Defino" },
  { subcodigo: 2422, descripcion: "No Defino" },
  { subcodigo: 2423, descripcion: "No Defino" },
  { subcodigo: 2424, descripcion: "No Defino" },
  { subcodigo: 2425, descripcion: "No Defino" },
  { subcodigo: 2426, descripcion: "No Defino" },
  { subcodigo: 2427, descripcion: "No Defino" },
  { subcodigo: 2428, descripcion: "No Defino" },
  { subcodigo: 2429, descripcion: "No Defino" },
  { subcodigo: 2430, descripcion: "No Defino" },
  { subcodigo: 2431, descripcion: "No Defino" },
  { subcodigo: 2432, descripcion: "No Defino" },
  { subcodigo: 2433, descripcion: "No Defino" },
  { subcodigo: 2434, descripcion: "No Defino" },
  { subcodigo: 2435, descripcion: "No Defino" },
  { subcodigo: 2436, descripcion: "No Defino" },
  { subcodigo: 2437, descripcion: "No Defino" },
  { subcodigo: 2438, descripcion: "No Defino" },
  { subcodigo: 2439, descripcion: "No Defino" },
  { subcodigo: 2440, descripcion: "No Defino" },
  { subcodigo: 2441, descripcion: "No Defino" },
  { subcodigo: 2442, descripcion: "No Defino" },
  { subcodigo: 2443, descripcion: "No Defino" },
  { subcodigo: 2444, descripcion: "No Defino" },
  { subcodigo: 2445, descripcion: "No Defino" },
  { subcodigo: 2446, descripcion: "No Defino" },
  { subcodigo: 2447, descripcion: "No Defino" },
  { subcodigo: 2448, descripcion: "No Defino" },
  { subcodigo: 2449, descripcion: "No Defino" },
  { subcodigo: 2450, descripcion: "No Defino" },
  { subcodigo: 2451, descripcion: "No Defino" },
  { subcodigo: 2452, descripcion: "No Defino" },
  { subcodigo: 2453, descripcion: "No Defino" },
  { subcodigo: 2454, descripcion: "No Defino" },
  { subcodigo: 2455, descripcion: "No Defino" },
  { subcodigo: 2456, descripcion: "No Defino" },
  { subcodigo: 2457, descripcion: "No Defino" },
  { subcodigo: 2458, descripcion: "No Defino" },
  { subcodigo: 2459, descripcion: "No Defino" },
  { subcodigo: 2460, descripcion: "No Defino" },
  { subcodigo: 2461, descripcion: "No Defino" },
  { subcodigo: 2462, descripcion: "No Defino" },
  { subcodigo: 2463, descripcion: "No Defino" },
  { subcodigo: 2464, descripcion: "No Defino" },
  { subcodigo: 2465, descripcion: "No Defino" },
  { subcodigo: 2466, descripcion: "No Defino" },
  { subcodigo: 2467, descripcion: "No Defino" },
  { subcodigo: 2468, descripcion: "No Defino" },
  { subcodigo: 2469, descripcion: "No Defino" },
  { subcodigo: 2470, descripcion: "No Defino" },
  { subcodigo: 2471, descripcion: "No Defino" },
  { subcodigo: 2472, descripcion: "No Defino" },
  { subcodigo: 2473, descripcion: "No Defino" },
  { subcodigo: 2474, descripcion: "No Defino" },
  { subcodigo: 2475, descripcion: "No Defino" },
  { subcodigo: 2476, descripcion: "No Defino" },
  { subcodigo: 2477, descripcion: "No Defino" },
  { subcodigo: 2478, descripcion: "No Defino" },
  { subcodigo: 2479, descripcion: "No Defino" },
  { subcodigo: 2480, descripcion: "No Defino" },
  { subcodigo: 2481, descripcion: "No Defino" },
  { subcodigo: 2482, descripcion: "No Defino" },
  { subcodigo: 2483, descripcion: "No Defino" },
  { subcodigo: 2484, descripcion: "No Defino" },
  { subcodigo: 2485, descripcion: "No Defino" },
  { subcodigo: 2486, descripcion: "No Defino" },
  { subcodigo: 2487, descripcion: "No Defino" },
  { subcodigo: 2488, descripcion: "No Defino" },
  { subcodigo: 2489, descripcion: "No Defino" },
  { subcodigo: 2490, descripcion: "No Defino" },
  { subcodigo: 2491, descripcion: "No Defino" },
  { subcodigo: 2492, descripcion: "No Defino" },
  { subcodigo: 2493, descripcion: "No Defino" },
  { subcodigo: 2494, descripcion: "No Defino" },
  { subcodigo: 2495, descripcion: "No Defino" },
  { subcodigo: 2496, descripcion: "No Defino" },
  { subcodigo: 2497, descripcion: "No Defino" },
  { subcodigo: 2498, descripcion: "No Defino" },
  { subcodigo: 2499, descripcion: "No Defino" },
  { subcodigo: 2500, descripcion: "No Defino" },
  { subcodigo: 2501, descripcion: "PREVENTIVE MAINTENANCE" },
];
